### ISSUE TITLE
Details about usage?

### ISSUE THREAD

**Issue by vkhurana** [Stefichen5/AutonomousControl#3]
Hi, Could you please share details on usage of this with an ESP32? A few questions that came up for me:
- Is the ESP32 connected in parallel with the controller on the desk?
   if so, how does the controller and the ESP32 work together (do they interfere?)
- It looks like the desk uses an RJ50 port, for the controller, would the ESP32 in series work (for a less obtrusive solution, that doesn't require disassembly of the controller in any way).
   Something like: Controller (RJ50 Male) -> (RJ50 Female) ESP32 (RJ50 Male) -> (RJ50 Female) Desk

This is a cool project!

**Comment by Stefichen5** [comment]
Hi,
I used  the ESP32 instead of the controller.
I ordered a second controller from Autonomous (for tinkering and also for the extra cable) and disconnected the cable. Then I just connected the pins of the cable to the pins of the ESP board.

I have never tried running the ESP and controller together. Since it uses UART which is not a bus system, there might be unwanted side effects.

**Comment by deepakkoirala** [comment]
There are multiple RXTX in ESP, you can use it as a relay as well. We can parallelly control from both ESP and the keypad. I am thinking to design a pcb for this.
